### ISSUE TITLE
Server crashes - 'Cannot find module 'babel-runtime/core-js/promise'

### ISSUE THREAD

**Issue by tconroy** [Dindaleon/hapi-react-starter-kit#20]
node version: 4.2.4
npm version: 2.4.12

when I try and run `npm run dev` I get the following:

```
$ npm run dev

> hapi-react-starter-kit@0.1.6 dev /Users/Tom/Code/Quickmeet
> cross-env NODE_ENV=development npm run start-dev


> hapi-react-starter-kit@0.1.6 start-dev /Users/Tom/Code/Quickmeet
> nodemon index.js

[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: webpack/devServer.js src/api.js src/issueToken.js src/server.js /Users/Tom/Code/Quickmeet/src/controllers/**/* src/controllers/***/* src/extensions/**/controllers/**/***/*
[nodemon] starting `node index.js`
module.js:340
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/promise'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Tom/Code/Quickmeet/src/server.js:3:16)
    at Module._compile (module.js:435:26)
    at loader (/Users/Tom/Code/Quickmeet/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Tom/Code/Quickmeet/node_modules/babel-core/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
[nodemon] app crashed - waiting for file changes before starting...
```

Have deleted `node_modules` and tried re-downloading several times, same error.

**Comment by Dindaleon** [comment]
Thanks for reporting this. Can you please try with node version 5.x

I am closing this issue. There are two possible solutions. Either update node to version 5 or install babel-runtime.

Please feel free to reopen the issue.
