### ISSUE TITLE
you npm i is failing

### ISSUE THREAD

**Issue by ghost** [Dindaleon/hapi-react-starter-kit#22]
trying your installation, but no luck.  any ideas why?

**Comment by zebapy** [comment]
You may need to supply some more information, like an error

**Comment by Dindaleon** [comment]
As zebapy indicated, please provide more information about the error you are getting; however, you can try updating your npm and node to their latest versions.

**Comment by ghost** [comment]
Just running an npm i, this is what i get - latest version nodejs/npm

```
ERROR in ./src/components/Dashboard.js
Module build failed: SyntaxError: /www/react/hapi-react-starter-kit/src/components/Dashboard.js: Unexpected token (86:0)
  84 | }
  85 |
> 86 | Dashboard.propTypes = {
     | ^
  87 |   user: PropTypes.object.isRequired,
  88 |   rooms: PropTypes.object.isRequired,
  89 |   createRoom: PropTypes.func.isRequired,
    at Parser.pp.raise (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:1425:13)
    at Parser.pp.unexpected (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:2905:8)
    at Parser.pp.expect (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:2899:33)
    at Parser.pp.parseCallExpressionArguments (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:576:12)
    at Parser.pp.parseSubscripts (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:548:29)
    at Parser.pp.parseExprSubscripts (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:519:15)
    at Parser.pp.parseMaybeUnary (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:489:19)
    at Parser.pp.parseExprOps (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:420:19)
    at Parser.pp.parseMaybeConditional (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:402:19)
    at Parser.pp.parseMaybeAssign (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:365:19)
    at Parser.pp.parseExpression (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:329:19)
    at Parser.pp.parseStatement (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:1950:19)
    at Parser.parseStatement (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:3578:22)
    at Parser.pp.parseBlockBody (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:2294:21)
    at Parser.pp.parseBlock (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:2275:8)
    at Parser.pp.parseFunctionBody (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:1130:22)
    at Parser.parseFunctionBody (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:3565:20)
    at Parser.pp.parseArrowExpression (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:1109:8)
    at Parser.pp.parseExprAtom (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:669:21)
    at Parser.parseExprAtom (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:4374:22)
    at Parser.pp.parseExprSubscripts (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:509:19)
    at Parser.pp.parseMaybeUnary (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:489:19)
    at Parser.pp.parseExprOps (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:420:19)
    at Parser.pp.parseMaybeConditional (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:402:19)
    at Parser.pp.parseMaybeAssign (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:365:19)
    at Parser.pp.parseClassProperty (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:2572:23)
    at Parser.parseClassProperty (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:3789:20)
    at Parser.pp.parseClassBody (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:2482:34)
    at Parser.pp.parseClass (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:2425:8)
    at Parser.pp.parseExport (/www/react/hapi-react-starter-kit/node_modules/babylon/index.js:2640:19)
 @ ./src/containers/DashboardContainer.js 15:17-51
```

**Comment by Dindaleon** [comment]
To install it, please use this:

```
git clone https://github.com/Dindaleon/hapi-react-starter-kit.git
```

instead of:

```
npm i hapi-react-starter-kit
```

That should do it, Please let me know if you encounter any more errors.

**Comment by ghost** [comment]
I installed that way actually.  Then run npm i in the folder.

**Comment by Dindaleon** [comment]
I just did a fresh install and it is working. So I cannot replicate the error. Try installing it again.

It must be something babel related. Please check that babel-core `v6.4.5` and babel-loader `v6.2.1` are installed and working.

**Comment by ghost** [comment]
worked this time.  thx

**Comment by Dindaleon** [comment]
@miganga I am glad you solved it. Do you care to explain what you had to do to solve it?

**Comment by meleksomai** [comment]
I'm facing the same problem explained in this issue. 

**packages.json file**

```
    "babel-core": "^6.5.2",
    "babel-loader": "^6.2.4",
```

**error**

```
Hash: fac4d7ac3db5022b80e4
Version: webpack 1.12.14
Time: 11970ms
                                   Asset     Size  Chunks             Chunk Names
        main-fac4d7ac3db5022b80e4.min.js  2.11 MB       0  [emitted]  main
1.IntlBundle-fac4d7ac3db5022b80e4.min.js   150 kB       1  [emitted]  IntlBundle
                      webpack.stats.json   6.8 kB          [emitted]
   [0] multi main 28 bytes {0} [built]
 [106] ./src/extensions ^\.\/.*$ 3.06 kB {0} [built]
 [320] ./src/themes ^\.\/.*$ 855 bytes {0} [built]
    + 666 hidden modules

ERROR in ./src/components/Dashboard.js
Module build failed: SyntaxError: /hapi/src/components/Dashboard.js: Unexpected token (86:0)
  84 | }
  85 |
> 86 | Dashboard.propTypes = {
     | ^
  87 |   user: PropTypes.object.isRequired,
  88 |   rooms: PropTypes.object.isRequired,
  89 |   createRoom: PropTypes.func.isRequired,
```

**Comment by Dindaleon** [comment]
@protactinium I just commit a fix for that file, please try again.
