### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ellerbrock** [Dindaleon/hapi-react-starter-kit#26]
hey there,

the build fails on osx:

npm:         3.10.5
node:        v6.3.0

throw this error after the webpack info:

```
Hash: 9c073095ca32ea2fbb62
Version: webpack 1.13.1
Time: 11241ms
                                   Asset     Size  Chunks             Chunk Names
        main-9c073095ca32ea2fbb62.min.js  2.15 MB       0  [emitted]  main
1.IntlBundle-9c073095ca32ea2fbb62.min.js   164 kB       1  [emitted]  IntlBundle
                      webpack.stats.json  7.28 kB          [emitted]
   [0] multi main 28 bytes {0} [built]
 [112] ./src/extensions ^\.\/.*$ 3.06 kB {0} [built]
 [335] ./src/themes ^\.\/.*$ 855 bytes {0} [built]
    + 675 hidden modules

ERROR in ./src/reducers/localeReducer.js
Module not found: Error: Cannot resolve module 'react-intl/lib/locale-data/en' in /fullstack/react/boilerplates/hapi-react-starter-kit/src/reducers
 @ ./src/reducers/localeReducer.js 11:10-50

ERROR in ./src/reducers/localeReducer.js
Module not found: Error: Cannot resolve module 'react-intl/lib/locale-data/es' in /fullstack/react/boilerplates/hapi-react-starter-kit/src/reducers
 @ ./src/reducers/localeReducer.js 15:10-50
```

and on the end this: 

```
> hapi-react-starter-kit@0.1.6 start /fullstack/react/boilerplates/hapi-react-starter-kit
> node index.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/xxx/.nvm/versions/node/v6.3.0/bin/node" "/Users/xxx/.nvm/versions/node/v6.3.0/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! hapi-react-starter-kit@0.1.6 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hapi-react-starter-kit@0.1.6 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hapi-react-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hapi-react-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hapi-react-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     fullstack/react/boilerplates/hapi-react-starter-kit/npm-debug.log
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/xxx/.nvm/versions/node/v6.3.0/bin/node',
1 verbose cli   '/Users/xxx/.nvm/versions/node/v6.3.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.5
3 info using node@v6.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hapi-react-starter-kit@0.1.6~prestart: hapi-react-starter-kit@0.1.6
6 silly lifecycle hapi-react-starter-kit@0.1.6~prestart: no script for prestart, continuing
7 info lifecycle hapi-react-starter-kit@0.1.6~start: hapi-react-starter-kit@0.1.6
8 verbose lifecycle hapi-react-starter-kit@0.1.6~start: unsafe-perm in lifecycle true
9 verbose lifecycle hapi-react-starter-kit@0.1.6~start: PATH: /Users/xxx/.nvm/versions/node/v6.3.0/lib/node_modules/npm/bin/node-gyp-bin:/fullstack/react/boilerplates/hapi-react-starter-kit/node_modules/.bin:/Users/xxx/.nvm/versions/node/v6.3.0/bin:/Users/xxx/.nvm/versions/node/v6.3.0/bin:/Users/xxx/.atom/:/Users/xxx/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
10 verbose lifecycle hapi-react-starter-kit@0.1.6~start: CWD: /fullstack/react/boilerplates/hapi-react-starter-kit
11 silly lifecycle hapi-react-starter-kit@0.1.6~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle hapi-react-starter-kit@0.1.6~start: Returned: code: 1  signal: null
13 info lifecycle hapi-react-starter-kit@0.1.6~start: Failed to exec start script
14 verbose stack Error: hapi-react-starter-kit@0.1.6 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/xxx/.nvm/versions/node/v6.3.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/xxx/.nvm/versions/node/v6.3.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid hapi-react-starter-kit@0.1.6
16 verbose cwd /fullstack/react/boilerplates/hapi-react-starter-kit
17 error Darwin 15.6.0
18 error argv "/Users/xxx/.nvm/versions/node/v6.3.0/bin/node" "/Users/xxx/.nvm/versions/node/v6.3.0/bin/npm" "start"
19 error node v6.3.0
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error hapi-react-starter-kit@0.1.6 start: `node index.js`
22 error Exit status 1
23 error Failed at the hapi-react-starter-kit@0.1.6 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the hapi-react-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs hapi-react-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls hapi-react-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

i found the link to your repo direct from the hapi website http://hapijs.com/resources and wondering if this repo is still suported? 

cheers maik

**Comment by etorhub** [comment]
Anything about this?
